#!/bin/sh

message=$1
currentBranch=$(git symbolic-ref --short -q HEAD)

if [ ! -z "$1" ]
then 
    git add *
    git commit -m "$message"
    git push origin $currentBranch
else
    echo "Commit message is required tp proceed with commit"
fi
